# === Основная информация ===
site_name: Лабораторные работы — Иван Пушкин
site_description: Портфолио лабораторных работ по курсу программирования
site_author: Иван Пушкин

# === Тема Material ===
theme:
  name: material
  language: ru
  palette:
    scheme: slate
    primary: indigo
    accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.follow

# === Навигация ===
nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Лабораторная работа №1: labs/lab1.md
      - Лабораторная работа №2: labs/lab2.md
      - Лабораторная работа №3: labs/lab3.md
      - Лабораторная работа №4: labs/lab4.md
      - Лабораторная работа №5: labs/lab5.md
      - Лабораторная работа №6: labs/lab6.md
      - Лабораторная работа №7: labs/lab7.md
      - Лабораторная работа №8: labs/lab8.md

# === Расширения Markdown ===
markdown_extensions:
  - codehilite:
      guess_lang: true
      linenums: false
  - tables
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg


# === Отключение поиска ===
plugins:
  - search:
      enabled: false

extra:
  copyright: ""
  generator: false